# PitchCamp worker config
name = "pitchcamp"
compatibility_date = "2026-01-01"
main = "worker.js"

[assets]
directory = "./"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "pitchcamp-db"
database_id = "83a2a916-1973-43dc-b7f9-250df9a77e5c"

[vars]
GOOGLE_WEBHOOK_URL = "https://script.google.com/macros/s/AKfycbw_TjR2Q3L1fI1WQLQR8RetbCss_s_oXMdk7ZKrRJ2_2tSNBgW54ZVfLR4wzbzDR5yk/exec"
